// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsModelDownloaded(arg1) {
  return window['go']['main']['App']['IsModelDownloaded'](arg1);
}

export function RemoveBackground(arg1, arg2) {
  return window['go']['main']['App']['RemoveBackground'](arg1, arg2);
}
