// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetModels():Promise<Array<main.ModelConfig>>;

export function GetVersion():Promise<string>;

export function IsModelDownloaded(arg1:string):Promise<boolean>;

export function RemoveBackground(arg1:string,arg2:string):Promise<string>;
